name: kwalps_st
description: "A new Flutter project."
publish_to: 'none' # Remove esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  crypto: ^3.0.6
  convert: ^3.1.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  intl: ^0.19.0
  file_picker: ^8.1.2
  excel: ^4.0.2   # para ler .xlsx (web/desktop/android)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/branding/my_stock_logo.png
